name: NT
description: "This is the official website of the artist Nicola Thomas, also known as NT"
markdown: redcarpet
highlighter: true
paginate: 5
paginate_path: "news/page:num"
url: "http://www.nicolathomas.com"